name: Main Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3]
    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: $(composer config cache-files-dir)
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"

      - run: yarn install --frozen-lockfile

      - name: Unit Tests
        run: echo "Run PHP UNIT TESTS"

      - name: Run Feature Tests
        run: echo "Run FEATURE Tests"
