name: Main Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1

  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          extensions: mbstring, dom, fileinfo, mysql
          coverage: xdebug

      - name: Checkout files
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"

      - run: yarn install
