name: Release new version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  release-job:
    name: Release Job - To do check that the PR is from same repo!
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged === true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: actions/setup-node
        uses: actions/setup-node@v1.4.1
        with:
          node-version: "13.9.0"

      - run: yarn install --frozen-lockfile

      - name: Set next version
        run: echo "::set-env name=version::$(yarn -s bump)"

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          extensions: mbstring, dom, fileinfo, mysql

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Show version
        run: echo ${{ version }}

      #- name: Monorepo release
      #  run: vendor/bin/monorepo-builder release $(yarn -s bump) --dry-run

      #- name: Monorepo split
      #  run: vendor/bin/monorepo-builder split


