name: Prepare release Workflow.

on:
  pull_request:
    types: [closed]
    branches:
      - 'release/**'

jobs:
  release-job:
    name: Release Job
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged === true
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo ${{ toJSON(github) }}}
      - name: Test
        run: echo ${{ toJSON(github.event.pull_request) }}}
